### ISSUE TITLE
Improve the editability.

### ISSUE THREAD

**Issue by datbu178** [yuval-alaluf/hyperstyle#12]
First of all, I want to thank you for your wonderful project! Another step forward in the StyleGAN Inversion problem.

The reconstruction quality is very good and close to optimization approaches. However, I found that the editability is not really good. When I change the latents in the age direction, the kid still have beards. And it doesn't even work with gender direction.
While I tried with PTI, it worked fine in both directions.

So I was wondering, is there a way to improve the editability better while sacrificing the reconstruction quality? Thank you.

**Comment by yuval-alaluf** [comment]
> When I change the latents in the age direction, the kid still have beards.

In some cases, it may be difficult to remove heavy beards when changing age. One option to try to mitigate this is to perform a smaller number of steps in inference (e.g., rather than 5, perform 1 or 2 steps). Hopefully that can help a bit. 

>  And it doesn't even work with gender direction.

How did you compute the gender direction? There may be more challenging edits such as gender that may not be possible out of the box. 
One option to try to improve editability while sacrificing reconstruction quality is to perhaps blend between the original pre-trained generator and the modified generator obtained with HyperStyle. Although I didn't try this myself, what I mean here is that the weights are currently updated as: `new_weight = old_weight * (1 + weight_delta).` Perhaps we can take (1/3) from the old generator and (2/3) from the new generator? That way, the shift is smaller and editing may be better. Again, I haven't tried this myself, but could be interesting to try. I hope that makes sense, but if not let me know :)

**Comment by datbu178** [comment]
Thank you for the answer!
Yes, both of your options improve editability while sacrificing reconstruction quality.
