### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for WEncoder:

### ISSUE THREAD

**Issue by Cagdas-Yilmaz** [yuval-alaluf/hyperstyle#21]
Hi, Thank you for your work. 

I want to train with custom dataset but I am getting the following error.

![image](https://drive.google.com/uc?export=view&id=1AjIbNxl-LLbOreuBDG26RWx86J3gyuG1)

In the --w_encoder_checkpoint_path section, I used the model I obtained from the training I made in the [encoder4editing
](https://github.com/omertov/encoder4editing) repository.

**Comment by Cagdas-Yilmaz** [comment]
- also stylegan model's output size is 512
- The w_encoder models you shared are 246 Mb. but the size of the model I got from the Encoder4editing training is 1 Gb.

**Comment by yuval-alaluf** [comment]
The WEncoder architecture is different than the e4e encoder. For example, e4e uses an FPN to output the latent codes and the WEncoder has a simpler architecture used to output a single latent code. 
 Therefore you are unable to load your encoder. 
If you do want to use your encoder for e4e you need to make a few changes: 
1. Change the `w_encoder_type` to match the encoder type of your e4e encoder. 
2. In the [pSp class](https://github.com/yuval-alaluf/hyperstyle/blob/main/models/encoders/psp.py), you need to add support for your encoder in the function `set_encoder`. For example, now we only support `WEncoder`, but you can add your class with your encoder type. 

> also stylegan model's output size is 512  

This is fine. We support different resolutions using the flag `--output_size`. You can set this to `512.

>  The w_encoder models you shared are 246 Mb. but the size of the model I got from the Encoder4editing training is 1 Gb.

As explained above, the WEncoder is a different architecture than the e4e encoder. It is a much more lightweight encoder that is used to generate a single latent code rather than multiple latent codes as is done in e4e. This explains the difference in the file weights.

**Comment by Cagdas-Yilmaz** [comment]
Thank you for helping,  which repository did you train WEncoder models?

**Comment by yuval-alaluf** [comment]
I used the e4e repo. There they call it SingleStyleCodeEncoder, but it is the same architecture and training scheme. 
You can use that encoder type and change the encoder type here from WEncoder to SingleStyleCodeEncoder

**Comment by Cagdas-Yilmaz** [comment]
Thank you so much, I will try to implement your suggestions.

**Comment by Winnie202** [comment]
> SingleStyleCodeEncoder

I have the same problem. Have you solved it？i try to replace psp class with e4e class, but do not work

**Comment by Winnie202** [comment]
> I used the e4e repo. There they call it SingleStyleCodeEncoder, but it is the same architecture and training scheme. You can use that encoder type and change the encoder type here from WEncoder to SingleStyleCodeEncoder

i have same problem ,i try to replace sps class with e4e class, then encoder_type is ProgressiveBackboneEncoder, but do not work

**Comment by Winnie202** [comment]
> I used the e4e repo. There they call it SingleStyleCodeEncoder, but it is the same architecture and training scheme. You can use that encoder type and change the encoder type here from WEncoder to SingleStyleCodeEncoder

in the e4e repo . Before the training, i added --encoder_type SingleStyleCodeEncoder, my hyperstyle is ready to train，thank you so much.

**Comment by yuval-alaluf** [comment]
Awesome

**Comment by shenhaiyoulan** [comment]
Hello！ 
I try to add --encoder_type SingStyleCodeEncoder in e4e repo, but i get an error:

Traceback (most recent call last):
  File "scripts/train.py", line 107, in <module>
    main()
  File "scripts/train.py", line 48, in main
    coach.train()
  File "./training/coach.py", line 108, in train
    self.check_for_progressive_training_update()
  File "./training/coach.py", line 156, in check_for_progressive_training_update
    self.net.encoder.set_progressive_stage(ProgressiveStage(i))
  File "/home/sd01/anaconda3/envs/e4e_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'BackboneEncoderUsingLastLayerIntoW' object has no attribute 'set_progressive_stage'

can you tell me how to modify it？ Thanks！ @yuval-alaluf @Winnie202
