### ISSUE TITLE
Training Process Problem

### ISSUE THREAD

**Issue by FeiiYin** [yuval-alaluf/hyperstyle#35]
During the training process, we first achieved a rough inversion result from e4e, which is a high-fidelity result. Then we use the hypernet to predict the weight deltas of stylegan convolution kernels.
During the training process, will the results first be blurry and then gradually be clear? or the image results are kept in the stylegan domain with high fidelity? Since the convolution weight deltas are hard to learn.

Thanks in advance!

**Comment by yuval-alaluf** [comment]
Since we learn modifications of the StyleGAN weights, if everything works correctly, the original outputs should be similar to the outputs you get from `e4e`. Then, throughout training, the reconstructions should gradually improve. 
In other words, the initial results shouldn't be blurry assuming that the reconstructions of e4e are good (as you mentioned).

**Comment by FeiiYin** [comment]
Thanks!
