### ISSUE TITLE
How to run code with CPU machine only

### ISSUE THREAD

**Issue by animesh-007** [yuval-alaluf/hyperstyle#44]
Hello,
Thank you for the great work. Is it possible for you to tell what modifications one has to do to run the code on the CPU only?

**Comment by yuval-alaluf** [comment]
In its current state, HyperStyle can't run on CPU. I think making it run on CPU will be quite difficult because StyleGAN2 relies on some specialized CUDA kernels. You can change these implementations to a native implementation in python, but getting them working will require some adjustments.

I hope the following thread can help: https://github.com/rosinality/stylegan2-pytorch/issues/89
