### ISSUE TITLE
the generated image is a little blur 

### ISSUE THREAD

**Issue by tengshaofeng** [yuval-alaluf/hyperstyle#46]
![tbq](https://user-images.githubusercontent.com/9246739/176576106-e905dbf7-690d-44b7-89e4-74bf6e22870b.png)
Thanks for your great work. It give me the best performance  as far as I know for reconstruction of real image.
But I found the reconstruct image is a litte blur.  The left of upload image is real image, and the right is the reconstructed one.
How can I get more clear image? They are all 1024x1024 without resizing  from 256 to 1024.

![tbq](https://user-images.githubusercontent.com/9246739/176578035-82fd3ab7-7469-4d16-aec1-127601261830.png)
the left of the next image is aligned and resize to 1024x1024, and the right is reconstructed one.

**Comment by yuval-alaluf** [comment]
Blurry images can sometimes occur because we are altering the actual StyleGAN generator so some artifacts could occur. One thing I've found that helps reduce the blurriness is reducing the number of steps used for inference. This isn't a perfect solution but it does help a bit from my experience. 
One other solution that could lead to less blurriness is trying to incorporate a new loss to the training of HyperStyle to try to reduce the blurriness of the reconstructions.

**Comment by tengshaofeng** [comment]
Thanks. By the way，How to define the new loss.



发自我的iPhone


------------------ Original ------------------
From: yuval-alaluf ***@***.***&gt;
Date: Sat,Jul 2,2022 11:36 PM
To: yuval-alaluf/hyperstyle ***@***.***&gt;
Cc: bojohn ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yuval-alaluf/hyperstyle] the generated image is a little blur (Issue #46)





 
Blurry images can sometimes occur because we are altering the actual StyleGAN generator so some artifacts could occur. One thing I've found that helps reduce the blurriness is reducing the number of steps used for inference. This isn't a perfect solution but it does help a bit from my experience.
 One other solution that could lead to less blurriness is trying to incorporate a new loss to the training of HyperStyle to try to reduce the blurriness of the reconstructions.

**Comment by McFredward** [comment]
I also experience this kind of blurriness with a non-facial domain trained Hyperstyle network. I guess that's the biggest issue with this model right now, because beside this, the model is surprisingly good at recreating fine details!

@yuval-alaluf So I would be also interested how you would adapt the loss to punish blur images (Iterating the generator only once during inference made no visible difference for me).

**Comment by tengshaofeng** [comment]
Another question. I found the performance is not good for smile of face editor.
![飞书20220420-101513_org](https://user-images.githubusercontent.com/9246739/177100292-f2d864fc-1ae6-4afd-b40d-e6fac1959520.png)

origin image,  reconsturcted image,  simle , laugh
The reconsturcted image is almost same as the origin image.
And it can really control smiling, but it is not good look, for example the teeth is ugly.
How can I get a better performance? thank you.

**Comment by yuval-alaluf** [comment]
Regarding the blurriness, I believe one possible loss could be something like a frequency-based loss in order to preserve the higher frequencies and prevent blurriness? Perhaps a discriminator-based loss could also assist here? I have not tried these myself, but from experience, these could possibly help the sharpness of the images.

**Comment by yuval-alaluf** [comment]
> How can I get a better performance? thank you.
You could possibly try decreasing the number of iterations to perform the inversion or constrain which layers are altered during the tuning process. This could help keep the model in a good place with respect to the original model

**Comment by tengshaofeng** [comment]
> This could help keep the model in a good place w
Thank you for your reply and advise.
