### ISSUE TITLE
Hyperstyle vs Restyle

### ISSUE THREAD

**Issue by zenjedi** [yuval-alaluf/hyperstyle#5]
Hi Yuval, firstly, fantastic job on your contributions across multiple GAN problems including **Restyle** and **Hyperstyle**. Can you advise if there are _clear benefits for real image inversion_ in Hyperstyle in comparison to Restyle?

Thanks!

**Comment by yuval-alaluf** [comment]
Really happy to see you've enjoyed the works 😄   

There are several advantages of HyperStyle compared to ReStyle, but I think the biggest one is editability. 

As we showed in the paper, ReStyle-pSp leads to some pretty good reconstructions. However, the problem with ReStyle is that these really good reconstructions come at the cost of latent codes which are not editable (in some cases even at all). In such a case, the latent code itself is a bit less useful to downstream tasks. 
With HyperStyle, we encode the image into W and apply edits on this W latent code. Since we only make small changes to the generator, we still preserve the high-quality images of SG and we get to leverage its semantically rich space which is great for editing. The use of this initial latent W code and the preservation of the original latent space makes HyperStyle much more suitable for editing.  In addition, directions that were learned in the original latent space work well on the modified generator, so you can seamlessly incorporate existing editing techniques with HyperStyle. 

Other advantages we tried showing in the work are domain adaptation and generalization to out-of-domain images. For example, we can apply offset learned by HyperStyle on the FFHQ generator to other fine-tuned generators. We show that when translating images to a fine-tuned generator, applying these offsets better preserves image features and identity. 

Hope this helps!

**Comment by zenjedi** [comment]
Thank you for your timely interactions on this forum, Yuval. This way, we get to also understand the invisible part of your work which has gone behind creating some really cool stuff, while I hope you get to see how we use your inventions.

Quick question: Though **ReStyle** brought in amazing low-latency optimisations in real-image encoding, one of the observations is that there were quite a few cases where inversion brought in aggressive changes to facial features, like adding wrinkles, etc, with even `n_iters_per_batch` is brought down from 5 to 3. When such an inverted image is fed to **StyleCLIP** for example, these errors get visually amplified.

Would these be automatically addressed because encoding happens first on the W space in **HyperStyle**?

**Comment by yuval-alaluf** [comment]
Interesting observation regarding ReStyle. Do you have an example of when you see these aggressive changes with ReStyle?

**Comment by zenjedi** [comment]
Here's an example. I've displayed the original image (a selfie) and **ReStyle**-based inverted image side-by-side. This may not show you the extent of distortion I've observed in certain cases, but may serve as an example. 

The extent of distortion is much lower with `n_iters_per_batch` of 2 or 3, but that brings down inversion accuracy.

I think it has to do with either boundaries within the face (like spectacles), or low light, or a combination of such factors. Because in most other cases, inversion is pretty good.

![restyle_inversion_creating_skin_wrinkles](https://user-images.githubusercontent.com/64598065/144595041-be013cd0-816a-4e20-89b2-789e0c963a6d.png)

**Comment by yuval-alaluf** [comment]
Very interesting! Have you tried running the image through HyperStyle? 
I've also noticed there is a slight discoloration here in the region near the eyes, which I've noticed in other images inverted by ReStyle before. I believe this may be caused due to the fact that ReStyle inverts into very far regions of W+, which behaves poorly. I think this also contributes to the poor editability ReStyle-pSp may encounter in some cases.
With HyperStyle, the hope is that inverting into W will help alleviate those artifacts and improve editability.

**Comment by zenjedi** [comment]
Inverted images are far superior with *HyperStyle*, but once I downstream them to *StyleCLIP*, manipulation leads to very different looking images. It's almost as if another real/inverted image was used in the first place. 

While alpha (manipulation strength) for a style works well, beta (disentanglment) effect is poor. This is based on my preliminary observation.

![hyperstyle_inversion_styleclip_generation_beard_a2_b0_15_iter_5](https://user-images.githubusercontent.com/64598065/144601719-3a6aa9c1-e8c3-41b2-80b1-aaff80cb995c.png)

If not for the above, **HyperStyle** would have been the go-to inversion model for us. Inversion (image in the centre) is pretty compelling. Fanstastic work, @yuval-alaluf

**Comment by zenjedi** [comment]
**HyperStyle Inversion + StyleCLIP editing:**
![hyperstyle_inversion_styleclip_generation_brad_pitt_curly_a2_b0_15_iter_5](https://user-images.githubusercontent.com/64598065/144701578-a5305f16-3d67-4704-9e17-4d8d5e4b89db.png)

**ReStyle Inversion + StyleCLIP editing:**
![restyle_inversion_styleclip_generation_brad_pitt_curly_a2_b0_15_iter_5](https://user-images.githubusercontent.com/64598065/144701610-cfa931ed-db5d-4cbb-84a0-081fe1ad98b5.png)

Like I said before, HyperStyle inversion is brilliant, but editing via StyleCLIP gets the **face to go a bit bonkers** compared to downstreaming from ReStyle, even though the styling works better with HyperStyle latents, @yuval-alaluf

**Comment by yuval-alaluf** [comment]
Did you make sure to apply the weight deltas when applying the StyleCLIP edits? 
I just ran the image myself and got the following edit with HyperStyle:
![pitt (13)](https://user-images.githubusercontent.com/37438467/144702607-93980cee-9a39-49dd-9080-6620f8037ae7.jpg)
These are two edited images with different editing strengths using StyleCLIP.  We can now see that the face identity is still well preserved. 
Notice that if you don't apply the weight deltas, you are pretty much using StyleCLIP over a W-latent code. Therefore, in the top image you posted you got a really nice edit, but the image is nothing like Pitt. 

I will add that the edits with HyperStyle are not artifact-free. There is of course still a trade-off between reconstruction and editability. But I like to think HyperStyle has a nice balance between the two. 

> StyleCLIP gets the face to go a bit bonkers compared to downstreaming from ReStyle

We can even see that ReStyle-pSp can't make any noticeable changes to the image so it makes sense the ID is preserved in ReStyle :)

**Comment by zenjedi** [comment]
No, I didn't apply weight deltas. Just went through the documentation and saw the command line option while running inference. You have exactly nailed the issue I'm facing then.

How do I programmatically enable saving and applying weight deltas?

**Comment by yuval-alaluf** [comment]
When running inference, there is a `sabe_weight_deltas` flag (details are in the readme). The reason it is not done by default is they do weigh a lot and I didn't want to make it true by default in the case you are performing inference on a large set of images.

**Comment by zenjedi** [comment]
HyperStyle encoding works well with StyleCLIP after applying weight deltas. But I see that a few edits like blue eyes do not work with HyperStyle latents, like how it works (well) with ReStyle. Would you know what might be happening?

**Comment by yuval-alaluf** [comment]
I'm surprising the editing of blue eyes worked with ReStyle. Did you apply the edit over ReStyle-pSp or ReStyle-e4e? In any case, there are edits that don't work well with StyleCLIP's global direction approach and should work better if you use the mapping approach for example.

**Comment by zenjedi** [comment]
> Did you apply the edit over ReStyle-pSp or   ##ReStyle-e4e?

ReStyle-psp
