### ISSUE TITLE
Hyperstyle training dataset structure.

### ISSUE THREAD

**Issue by Zeeshan75** [yuval-alaluf/hyperstyle#54]
Hi @yuval-alaluf, Thanks for the repository, It's interesting.

I thought of training on the custom dataset. But In the 2nd point of "**preparing your data**". There we have source and target data paths for both train and test sets. 

I have around 10k images, do I need to split the data in source and target and again in train and test sets (Or) do I need to generate inversions and keep them in source and all images in the target folder?

Please give some references to custom transforms(what are the transforms available?).

Thanks in advance.

**Comment by yuval-alaluf** [comment]
Basically, the source and target paths can be identical since we are training an encoder to perform inversion. What you can do is split the data into train and test in advance (say make a directory with 9k images and another directory with 1k images). 
If you want to try to reduce the memory consumption slightly, you can follow the steps [here](https://github.com/yuval-alaluf/hyperstyle#pre-extracting-initial-inversions) and pre-extract the inversions. This is not a requirement though and I would start without this. 
Regarding the transforms, you can define any transforms you feel fit your domain.
We define some standard transforms [here](https://github.com/yuval-alaluf/hyperstyle/blob/main/configs/transforms_config.py#L15) but you can use any transforms you would like just like you would do with any Pytorch code.
